# == Schema Information
#
# Table name: estudantes
#
#  id                 :integer          not null, primary key
#  nome               :string(255)
#  numero_de_registro :string(255)
#  situacao           :integer
#  created_at         :datetime
#  updated_at         :datetime
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EstudantesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Estudante. As you add validations to Estudante, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:estudante).attributes.except("id", "created_at", "updated_at")
  }

  let(:invalid_attributes) {
    { nome: '', numero_de_registro: '', situacao: '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EstudantesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all estudantes as @estudantes" do
      estudante = Estudante.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:estudantes)).to eq([estudante])
    end
  end

  describe "GET show" do
    it "assigns the requested estudante as @estudante" do
      estudante = Estudante.create! valid_attributes
      get :show, {:id => estudante.to_param}, valid_session
      expect(assigns(:estudante)).to eq(estudante)
    end
  end

  describe "GET new" do
    it "assigns a new estudante as @estudante" do
      get :new, {}, valid_session
      expect(assigns(:estudante)).to be_a_new(Estudante)
    end
  end

  describe "GET edit" do
    it "assigns the requested estudante as @estudante" do
      estudante = Estudante.create! valid_attributes
      get :edit, {:id => estudante.to_param}, valid_session
      expect(assigns(:estudante)).to eq(estudante)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Estudante" do
        expect {
          post :create, {:estudante => valid_attributes}, valid_session
        }.to change(Estudante, :count).by(1)
      end

      it "assigns a newly created estudante as @estudante" do
        post :create, {:estudante => valid_attributes}, valid_session
        expect(assigns(:estudante)).to be_a(Estudante)
        expect(assigns(:estudante)).to be_persisted
      end

      it "redirects to the created estudante" do
        post :create, {:estudante => valid_attributes}, valid_session
        expect(response).to redirect_to(Estudante.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved estudante as @estudante" do
        post :create, {:estudante => invalid_attributes}, valid_session
        expect(assigns(:estudante)).to be_a_new(Estudante)
      end

      it "re-renders the 'new' template" do
        post :create, {:estudante => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        {
          nome: Faker::Name.name,
          numero_de_registro: Faker::Number.hexadecimal(10),
          situacao: Faker::Number.number(5)
        }
      }

      it "updates the requested estudante" do
        estudante = Estudante.create! valid_attributes
        put :update, {:id => estudante.to_param, :estudante => new_attributes}, valid_session
        old = estudante.clone
        estudante.reload
        expect(old.nome).not_to eq(estudante.nome)
        expect(old.numero_de_registro).not_to eq(estudante.numero_de_registro)
        expect(old.situacao).not_to eq(estudante.situacao)
        expect(old.id).to eq(estudante.id)
      end

      it "assigns the requested estudante as @estudante" do
        estudante = Estudante.create! valid_attributes
        put :update, {:id => estudante.to_param, :estudante => valid_attributes}, valid_session
        expect(assigns(:estudante)).to eq(estudante)
      end

      it "redirects to the estudante" do
        estudante = Estudante.create! valid_attributes
        put :update, {:id => estudante.to_param, :estudante => valid_attributes}, valid_session
        expect(response).to redirect_to(estudante)
      end
    end

    describe "with invalid params" do
      it "assigns the estudante as @estudante" do
        estudante = Estudante.create! valid_attributes
        put :update, {:id => estudante.to_param, :estudante => invalid_attributes}, valid_session
        expect(assigns(:estudante)).to eq(estudante)
      end

      it "re-renders the 'edit' template" do
        estudante = Estudante.create! valid_attributes
        put :update, {:id => estudante.to_param, :estudante => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested estudante" do
      estudante = Estudante.create! valid_attributes
      expect {
        delete :destroy, {:id => estudante.to_param}, valid_session
      }.to change(Estudante, :count).by(-1)
    end

    it "redirects to the estudantes list" do
      estudante = Estudante.create! valid_attributes
      delete :destroy, {:id => estudante.to_param}, valid_session
      expect(response).to redirect_to(estudantes_url)
    end
  end

end
